# Auto-generated by Aspire for EF Core migration bundle.
FROM mcr.microsoft.com/dotnet/runtime:10.0
WORKDIR /app
COPY --chmod=0755 db2-migrations /app/efbundle
ENTRYPOINT /app/efbundle -v --connection "$ConnectionStrings__db2"
