//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class JavaHostingExtensions
    {
        [AspireExport("addJavaAppWithJar")]
        public static ApplicationModel.IResourceBuilder<Java.JavaAppResource> AddJavaApp(this IDistributedApplicationBuilder builder, string name, string appDirectory, string jarPath, params string[] args) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Java.JavaAppResource> AddJavaApp(this IDistributedApplicationBuilder builder, string name, string appDirectory) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Java.JavaContainerResource> AddJavaContainer(this IDistributedApplicationBuilder builder, string name, string image, string? tag = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Java.JavaAppResource> AddQuarkusApp(this IDistributedApplicationBuilder builder, string name, string appDirectory) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Java.JavaAppResource> AddSpringBootApp(this IDistributedApplicationBuilder builder, string name, string appDirectory) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithGradleBuild<T>(this ApplicationModel.IResourceBuilder<T> builder, params string[] args)
            where T : Java.JavaAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithGradleTask<T>(this ApplicationModel.IResourceBuilder<T> builder, string task, params string[] args)
            where T : Java.JavaAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithJarArtifact<T>(this ApplicationModel.IResourceBuilder<T> builder, string jarPath)
            where T : Java.JavaAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithJvmArgs<T>(this ApplicationModel.IResourceBuilder<T> builder, params string[] args)
            where T : Java.IJavaAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithMainClass<T>(this ApplicationModel.IResourceBuilder<T> builder, string mainClass)
            where T : Java.JavaAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithMavenBuild<T>(this ApplicationModel.IResourceBuilder<T> builder, params string[] args)
            where T : Java.JavaAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithMavenGoal<T>(this ApplicationModel.IResourceBuilder<T> builder, string goal, params string[] args)
            where T : Java.JavaAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithOtelAgent<T>(this ApplicationModel.IResourceBuilder<T> builder, string agentPath)
            where T : Java.JavaAppResource { throw null; }

        [AspireExport("withOtelAgentDefaultPath")]
        public static ApplicationModel.IResourceBuilder<T> WithOtelAgent<T>(this ApplicationModel.IResourceBuilder<T> builder)
            where T : Java.JavaAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithWrapperPath<T>(this ApplicationModel.IResourceBuilder<T> builder, string wrapperPath)
            where T : Java.JavaAppResource { throw null; }
    }
}

namespace Aspire.Hosting.Java
{
    public partial interface IJavaAppResource : ApplicationModel.IResourceWithEnvironment, ApplicationModel.IResource
    {
    }

    [AspireExport(ExposeProperties = true)]
    public partial class JavaAppResource : ApplicationModel.ExecutableResource, IJavaAppResource, ApplicationModel.IResourceWithEnvironment, ApplicationModel.IResource, IResourceWithServiceDiscovery, ApplicationModel.IResourceWithEndpoints, ApplicationModel.IContainerFilesDestinationResource
    {
        public JavaAppResource(string name, string workingDirectory) : base(default!, default!, default!) { }
    }

    [AspireExport(ExposeProperties = true)]
    public partial class JavaContainerResource : ApplicationModel.ContainerResource, IJavaAppResource, ApplicationModel.IResourceWithEnvironment, ApplicationModel.IResource, IResourceWithServiceDiscovery, ApplicationModel.IResourceWithEndpoints
    {
        public JavaContainerResource(string name, string? entrypoint = null) : base(default!, default) { }
    }
}