<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="System.IO.Hashing" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Aspire.TestTools\*.cs" LinkBase="Aspire.TestTools" />
    <Content Include="..\..\.github\workflows\create-failing-test-issue-tracking.js" Link="create-failing-test-issue-tracking.js" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\.github\workflows\tracking-issue-gh-api.js" Link="tracking-issue-gh-api.js" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\.github\workflows\tracking-issue.js" Link="tracking-issue.js" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
