//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class RadiusCloudProviderExtensions
    {
        [AspireExportIgnore(Reason = "The credential-selection callback exposes the in-flight provider builder interface, which the ATS exporter cannot render (ASPIREEXPORT008).")]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS003", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> WithAwsProvider(this ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> builder, string accountId, string region, System.Action<Radius.CloudProviders.IAwsRadiusProviderBuilder> configure) { throw null; }

        [AspireExportIgnore(Reason = "The credential-selection callback exposes the in-flight provider builder interface, which the ATS exporter cannot render (ASPIREEXPORT008).")]
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS003", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> WithAzureProvider(this ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> builder, string subscriptionId, string resourceGroup, System.Action<Radius.CloudProviders.IAzureRadiusProviderBuilder> configure) { throw null; }
    }

    public static partial class RadiusExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> AddRadiusEnvironment(this IDistributedApplicationBuilder builder, string name) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "RadiusInfrastructureOptions customization callbacks are not ATS-compatible.")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> ConfigureRadiusInfrastructure(this ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> builder, System.Action<Radius.Publishing.RadiusInfrastructureOptions> configure) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS057", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ProjectResource> WithContainerImage(this ApplicationModel.IResourceBuilder<ApplicationModel.ProjectResource> builder, string image) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> WithNamespace(this ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> builder, string kubernetesNamespace) { throw null; }
    }

    public static partial class RadiusRecipeParameterExtensions
    {
        [AspireExportIgnore(Reason = "The configure callback over a mutable dictionary is not representable in the ATS catalog (ASPIREEXPORT008).")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> WithRecipeParameters(this ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> builder, System.Action<System.Collections.Generic.IDictionary<string, object>> configure) { throw null; }

        [AspireExportIgnore(Reason = "The configure callback over a mutable dictionary is not representable in the ATS catalog (ASPIREEXPORT008).")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> WithRecipeParameters(this ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> builder, string resourceType, System.Action<System.Collections.Generic.IDictionary<string, object>> configure) { throw null; }
    }

    public static partial class RadiusSecretStoreConsumerExtensions
    {
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS006", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "Experimental Radius secret-store consumer surface; there is no polyglot ATS equivalent yet.")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> WithBicepRegistryAuthentication(this ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> radius, string registryHost, ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource> store) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS006", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "Experimental Radius secret-store consumer surface; there is no polyglot ATS equivalent yet.")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> WithRecipeEnvironmentSecret(this ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> radius, string variableName, ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource> store, string key) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS006", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "Experimental Radius secret-store consumer surface; there is no polyglot ATS equivalent yet.")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> WithTerraformGitAuthentication(this ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> radius, string gitHost, ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource> store) { throw null; }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS006", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class RadiusSecretStoreDataBuilder
    {
        internal RadiusSecretStoreDataBuilder() { }

        public RadiusSecretStoreDataBuilder Add(string key, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> parameter, Radius.RadiusSecretStoreEncoding? encoding = null) { throw null; }
    }

    public static partial class RadiusSecretStoreExtensions
    {
        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS006", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "Experimental Radius secret-store surface; there is no polyglot ATS equivalent yet.")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource> AddRadiusSecretStore(this IDistributedApplicationBuilder builder, string name, Radius.RadiusSecretStoreType type) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS006", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "Experimental Radius secret-store surface; the data-binding callback is not ATS-compatible.")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource> WithData(this ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource> store, System.Action<RadiusSecretStoreDataBuilder> configure) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS006", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "Experimental Radius secret-store surface; the data binding is not ATS-compatible.")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource> WithData(this ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource> store, string key, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> parameter, Radius.RadiusSecretStoreEncoding? encoding = null) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS006", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "Experimental Radius secret-store surface; there is no polyglot ATS equivalent yet.")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource> WithExistingSecret(this ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource> store, string namespaceAndName, params string[] keys) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS006", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "Sealed-secret deploy-timing knob with no polyglot ATS equivalent.")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource> WithMaterializationTimeout(this ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource> store, System.TimeSpan timeout) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS006", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "Experimental Radius secret-store surface; there is no polyglot ATS equivalent yet.")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource> WithSealedSecret(this ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource> store, string manifestPath, params string[] keys) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS006", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        [AspireExportIgnore(Reason = "Experimental Radius secret-store surface; the population callback is not ATS-compatible.")]
        public static ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> WithSecretStore(this ApplicationModel.IResourceBuilder<Radius.RadiusEnvironmentResource> radius, string name, Radius.RadiusSecretStoreType type, System.Action<ApplicationModel.IResourceBuilder<Radius.RadiusSecretStoreResource>> configure) { throw null; }
    }
}

namespace Aspire.Hosting.Radius
{
    [AspireExport(ExposeProperties = true)]
    public sealed partial class RadiusEnvironmentResource : ApplicationModel.Resource, ApplicationModel.IComputeEnvironmentResource, ApplicationModel.IResource
    {
        public RadiusEnvironmentResource(string name) : base(default!) { }

        public string Namespace { get { throw null; } set { } }

        public ApplicationModel.IComputeEnvironmentResource? OwningComputeEnvironment { get { throw null; } set { } }

        ApplicationModel.ReferenceExpression ApplicationModel.IComputeEnvironmentResource.GetEndpointPropertyExpression(ApplicationModel.EndpointReferenceExpression endpointReferenceExpression) { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("ASPIRECOMPUTE002", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
        public ApplicationModel.ReferenceExpression GetHostAddressExpression(ApplicationModel.EndpointReference endpointReference) { throw null; }
    }

    public sealed partial class RadiusProviderReference
    {
        internal RadiusProviderReference() { }

        public static RadiusProviderReference AwsAccountId { get { throw null; } }

        public static RadiusProviderReference AwsRegion { get { throw null; } }

        public static RadiusProviderReference AzureResourceGroup { get { throw null; } }

        public static RadiusProviderReference AzureSubscriptionId { get { throw null; } }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS006", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public enum RadiusSecretStoreEncoding
    {
        Raw = 0,
        Base64 = 1
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS006", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class RadiusSecretStoreResource : ApplicationModel.Resource
    {
        internal RadiusSecretStoreResource() : base(default!) { }

        public System.TimeSpan MaterializationTimeout { get { throw null; } }

        public RadiusSecretStoreType Type { get { throw null; } }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS006", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public enum RadiusSecretStoreType
    {
        Generic = 0,
        Certificate = 1,
        BasicAuthentication = 2,
        AzureWorkloadIdentity = 3,
        AwsIrsa = 4
    }
}

namespace Aspire.Hosting.Radius.CloudProviders
{
    public partial interface IAwsRadiusProviderBuilder
    {
        IAwsRadiusProviderBuilder WithAccessKey(ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> accessKeyId, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> secretAccessKey);
        IAwsRadiusProviderBuilder WithIrsa(string iamRoleArn);
    }

    public partial interface IAzureRadiusProviderBuilder
    {
        IAzureRadiusProviderBuilder WithServicePrincipal(string tenantId, string clientId, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> clientSecret);
        IAzureRadiusProviderBuilder WithWorkloadIdentity(string tenantId, string clientId);
    }
}

namespace Aspire.Hosting.Radius.Publishing
{
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class RadiusInfrastructureOptions
    {
        public System.Collections.Generic.List<Constructs.RadiusApplicationConstruct> Applications { get { throw null; } }

        public System.Collections.Generic.List<Constructs.RadiusContainerConstruct> Containers { get { throw null; } }

        public System.Collections.Generic.List<Constructs.RadiusEnvironmentConstruct> Environments { get { throw null; } }

        public System.Collections.Generic.List<Constructs.LegacyApplicationConstruct> LegacyApplications { get { throw null; } }

        public System.Collections.Generic.List<Constructs.LegacyApplicationEnvironmentConstruct> LegacyEnvironments { get { throw null; } }

        public System.Collections.Generic.List<Azure.Provisioning.ProvisioningParameter> Parameters { get { throw null; } }

        public System.Collections.Generic.List<Constructs.RadiusRecipePackConstruct> RecipePacks { get { throw null; } }

        public System.Collections.Generic.List<Constructs.RadiusResourceTypeConstruct> ResourceTypeInstances { get { throw null; } }

        public System.Collections.Generic.List<Constructs.RadiusSecretStoreConstruct> SecretStores { get { throw null; } }
    }
}

namespace Aspire.Hosting.Radius.Publishing.Constructs
{
    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class ConnectionConstruct : Azure.Provisioning.Primitives.ProvisionableConstruct
    {
        public Azure.Provisioning.BicepValue<string> Source { get { throw null; } set { } }

        protected override void DefineProvisionableProperties() { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class ContainerEnvVarConstruct : Azure.Provisioning.Primitives.ProvisionableConstruct
    {
        public Azure.Provisioning.BicepValue<string> Value { get { throw null; } set { } }

        protected override void DefineProvisionableProperties() { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class ContainerPortConstruct : Azure.Provisioning.Primitives.ProvisionableConstruct
    {
        public Azure.Provisioning.BicepValue<int> ContainerPort { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> Protocol { get { throw null; } set { } }

        protected override void DefineProvisionableProperties() { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class LegacyApplicationConstruct : Azure.Provisioning.Primitives.ProvisionableResource
    {
        public LegacyApplicationConstruct(string bicepIdentifier) : base(default!, default, default) { }

        public Azure.Provisioning.BicepValue<string> ApplicationName { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> EnvironmentId { get { throw null; } set { } }

        protected override void DefineProvisionableProperties() { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class LegacyApplicationEnvironmentConstruct : Azure.Provisioning.Primitives.ProvisionableResource
    {
        public LegacyApplicationEnvironmentConstruct(string bicepIdentifier) : base(default!, default, default) { }

        public Azure.Provisioning.BicepValue<string> AwsScope { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> AzureScope { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> ComputeKind { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> ComputeNamespace { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> EnvironmentName { get { throw null; } set { } }

        public Azure.Provisioning.BicepDictionary<object> RecipeConfig { get { throw null; } set { } }

        public Azure.Provisioning.BicepDictionary<Azure.Provisioning.BicepDictionary<LegacyRecipeEntryConstruct>> Recipes { get { throw null; } set { } }

        protected override void DefineProvisionableProperties() { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class LegacyRecipeEntryConstruct : Azure.Provisioning.Primitives.ProvisionableConstruct
    {
        public Azure.Provisioning.BicepDictionary<object> Parameters { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> TemplateKind { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> TemplatePath { get { throw null; } set { } }

        protected override void DefineProvisionableProperties() { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class RadiusApplicationConstruct : Azure.Provisioning.Primitives.ProvisionableResource
    {
        public RadiusApplicationConstruct(string bicepIdentifier) : base(default!, default, default) { }

        public Azure.Provisioning.BicepValue<string> ApplicationName { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> EnvironmentId { get { throw null; } set { } }

        protected override void DefineProvisionableProperties() { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class RadiusContainerConstruct : Azure.Provisioning.Primitives.ProvisionableResource
    {
        public RadiusContainerConstruct(string bicepIdentifier, string containerName) : base(default!, default, default) { }

        public Azure.Provisioning.BicepValue<string> ApplicationId { get { throw null; } set { } }

        public Azure.Provisioning.BicepDictionary<ConnectionConstruct> Connections { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> ContainerName { get { throw null; } set { } }

        public Azure.Provisioning.BicepDictionary<ContainerEnvVarConstruct> Env { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> EnvironmentId { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> Image { get { throw null; } set { } }

        public Azure.Provisioning.BicepDictionary<ContainerPortConstruct> Ports { get { throw null; } set { } }

        protected override void DefineProvisionableProperties() { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class RadiusEnvironmentConstruct : Azure.Provisioning.Primitives.ProvisionableResource
    {
        public RadiusEnvironmentConstruct(string bicepIdentifier) : base(default!, default, default) { }

        public Azure.Provisioning.BicepValue<string> AwsAccountId { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> AwsRegion { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> AzureResourceGroupName { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> AzureSubscriptionId { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> EnvironmentName { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> KubernetesNamespace { get { throw null; } set { } }

        public Azure.Provisioning.BicepList<string> RecipePacks { get { throw null; } set { } }

        protected override void DefineProvisionableProperties() { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class RadiusRecipePackConstruct : Azure.Provisioning.Primitives.ProvisionableResource
    {
        public RadiusRecipePackConstruct(string bicepIdentifier) : base(default!, default, default) { }

        public Azure.Provisioning.BicepValue<string> PackName { get { throw null; } set { } }

        public Azure.Provisioning.BicepDictionary<RecipeEntryConstruct> Recipes { get { throw null; } set { } }

        protected override void DefineProvisionableProperties() { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class RadiusResourceTypeConstruct : Azure.Provisioning.Primitives.ProvisionableResource
    {
        public RadiusResourceTypeConstruct(string bicepIdentifier, string resourceType, string apiVersion) : base(default!, default, default) { }

        public Azure.Provisioning.BicepValue<string> ApplicationId { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> EnvironmentId { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> RecipeName { get { throw null; } set { } }

        public Azure.Provisioning.BicepDictionary<object> RecipeParameters { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> ResourceName { get { throw null; } set { } }

        protected override void DefineProvisionableProperties() { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class RadiusSecretStoreConstruct : Azure.Provisioning.Primitives.ProvisionableResource
    {
        public RadiusSecretStoreConstruct(string bicepIdentifier) : base(default!, default, default) { }

        public Azure.Provisioning.BicepValue<string> ApplicationId { get { throw null; } set { } }

        public Azure.Provisioning.BicepDictionary<RadiusSecretStoreDataEntryConstruct> Data { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> EnvironmentId { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> ResourceReference { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> StoreName { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> StoreType { get { throw null; } set { } }

        protected override void DefineProvisionableProperties() { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class RadiusSecretStoreDataEntryConstruct : Azure.Provisioning.Primitives.ProvisionableConstruct
    {
        public Azure.Provisioning.BicepValue<string> Encoding { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> Value { get { throw null; } set { } }

        protected override void DefineProvisionableProperties() { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("ASPIRERADIUS004", UrlFormat = "https://aka.ms/aspire/diagnostics/{0}")]
    public sealed partial class RecipeEntryConstruct : Azure.Provisioning.Primitives.ProvisionableConstruct
    {
        public Azure.Provisioning.BicepDictionary<object> Parameters { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> RecipeKind { get { throw null; } set { } }

        public Azure.Provisioning.BicepValue<string> RecipeLocation { get { throw null; } set { } }

        protected override void DefineProvisionableProperties() { }
    }
}