//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class RustHostingExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<Rust.RustAppResource> AddRustApp(this IDistributedApplicationBuilder builder, string name, string appDirectory) { throw null; }

        [AspireExportIgnore(Reason = "Callback-based cargo arguments are not expressible in polyglot app hosts.")]
        public static ApplicationModel.IResourceBuilder<T> WithCargoArgs<T>(this ApplicationModel.IResourceBuilder<T> builder, System.Action<Rust.RustCargoArgsCallbackContext> callback)
            where T : Rust.RustAppResource { throw null; }

        [AspireExportIgnore(Reason = "Callback-based cargo arguments are not expressible in polyglot app hosts.")]
        public static ApplicationModel.IResourceBuilder<T> WithCargoArgs<T>(this ApplicationModel.IResourceBuilder<T> builder, System.Func<Rust.RustCargoArgsCallbackContext, System.Threading.Tasks.Task> callback)
            where T : Rust.RustAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithCargoArgs<T>(this ApplicationModel.IResourceBuilder<T> builder, params string[] args)
            where T : Rust.RustAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithCargoBinTarget<T>(this ApplicationModel.IResourceBuilder<T> builder, string binName)
            where T : Rust.RustAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithCargoExample<T>(this ApplicationModel.IResourceBuilder<T> builder, string exampleName)
            where T : Rust.RustAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithCargoFeatures<T>(this ApplicationModel.IResourceBuilder<T> builder, params string[] features)
            where T : Rust.RustAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithCargoLocked<T>(this ApplicationModel.IResourceBuilder<T> builder, bool locked = true)
            where T : Rust.RustAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithCargoManifestPath<T>(this ApplicationModel.IResourceBuilder<T> builder, string manifestPath)
            where T : Rust.RustAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithCargoPackage<T>(this ApplicationModel.IResourceBuilder<T> builder, string packageName)
            where T : Rust.RustAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithCargoProfile<T>(this ApplicationModel.IResourceBuilder<T> builder, string profileName)
            where T : Rust.RustAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithCargoReleaseBuild<T>(this ApplicationModel.IResourceBuilder<T> builder, bool releaseBuild = true)
            where T : Rust.RustAppResource { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithCargoTarget<T>(this ApplicationModel.IResourceBuilder<T> builder, string target)
            where T : Rust.RustAppResource { throw null; }
    }
}

namespace Aspire.Hosting.Rust
{
    [AspireExport(ExposeProperties = true)]
    public partial class RustAppResource : ApplicationModel.ExecutableResource, IResourceWithServiceDiscovery, ApplicationModel.IResourceWithEndpoints, ApplicationModel.IResource, ApplicationModel.IContainerFilesDestinationResource
    {
        public RustAppResource(string name, string workingDirectory) : base(default!, default!, default!) { }
    }

    public sealed partial class RustCargoArgsCallbackContext
    {
        public RustCargoArgsCallbackContext(RustAppResource resource, System.Collections.Generic.IList<string> args, System.Threading.CancellationToken cancellationToken = default) { }

        public System.Collections.Generic.IList<string> Args { get { throw null; } }

        public System.Threading.CancellationToken CancellationToken { get { throw null; } }

        public RustAppResource Resource { get { throw null; } }
    }
}